[package]
name = "emoji_builder"
version = "0.1.0"
authors = ["Constantin A. <emoji.builder@c1710.de>"]
edition = "2018"
license = "Apache-2.0"


[dependencies]
resvg = {version = "0.7.0", features = ["raqote-backend"]}
oxipng = "2.2.0"
regex = "1.1.6"
hex = "0.3"
lazy_static = "1.3.0"
libc = "0.2.58"
csv = "1"
sha2 = "0.8.0"
itertools = "0.8.0"
rand = "0.6.5"
rayon = "1.0"
remove_dir_all = "0.5.1"
clap = {version = "2.33", features = ["yaml"]}
png = "0.14.1"
tempfile = "3.0.8"
usvg = "0.7.0"
digest = "0.8.0"

[build-dependencies]
cc = "1.0.37"

