[package]
name = "emoji_builder"
version = "0.1.0"
authors = ["Constantin A. <10349490+C1710@users.noreply.github.com>"]


[dependencies]
resvg = {git = "https://github.com/RazrFalcon/resvg", branch="raqote-backend", features = ["raqote-backend"]}
oxipng = "2.2.0"
threadpool = "1.7.1"
tokio-threadpool = "0.1.14"
regex = "1.1.6"
hex = "0.3"
lazy_static = "1.3.0"
libc = "0.2.58"
csv = "1"
sha2 = "0.8.0"
itertools = "0.8.0"
rand = "0.6.5"

[build-dependencies]
cc = "1.0.37"

